apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo--wordpress

resources:
- ../../components/wordpress-app/

secretGenerator:
- name: mysql-secret
  type: Opaque
  envs:
  - secrets.env
  behavior: create
